In [2]:
import pandas as pd
import numpy as np

In [3]:
school_data_file = "Resources/schools_complete.csv"
student_data_file = "Resources/students_complete.csv"

school_data = pd.read_csv(school_data_file)
student_data = pd.read_csv(student_data_file)
                          
school_data_set = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_set

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type1,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
23,23,Christopher Parker,M,9th,Huang High School,81,68,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
26,26,Melanie Decker,F,9th,Huang High School,63,85,0,District,2917,1910635
27,27,Tracey Oconnor,F,10th,Huang High School,80,58,0,District,2917,1910635
28,28,Kelly James,F,11th,Huang High School,73,55,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99,14,Charter,1635,1043130
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93,14,Charter,1635,1043130
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83,14,Charter,1635,1043130
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93,14,Charter,1635,1043130
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87,14,Charter,1635,1043130
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74,14,Charter,1635,1043130
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95,14,Charter,1635,1043130
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81,14,Charter,1635,1043130
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89,14,Charter,1635,1043130
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93,14,Charter,1635,1043130
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75,14,Charter,1635,1043130
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73,14,Charter,1635,1043130
39152,39152,Lori Moore,F,9th,Thomas High School,98,84,14,Charter,1635,1043130
39153,39153,William Hubbard,M,9th,Thomas High School,80,75,14,Charter,1635,1043130
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71,14,Charter,1635,1043130
39155,39155,John Brooks,M,10th,Thomas High School,92,98,14,Charter,1635,1043130
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95,14,Charter,1635,1043130
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94,14,Charter,1635,1043130
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90,14,Charter,1635,1043130
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72,14,Charter,1635,1043130
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86,14,Charter,1635,1043130
39161,39161,April Reyes,F,10th,Thomas High School,70,84,14,Charter,1635,1043130
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77,14,Charter,1635,1043130
39163,39163,John Reese,M,11th,Thomas High School,90,75,14,Charter,1635,1043130
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76,14,Charter,1635,1043130
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130

In [4]:
renamed = school_data_set.rename(columns = {"student_name": "Student Name", "gender": "Gender", "grade": "Grade",
                                           "school_name": "School Name", "reading_score": "Reading Score",
                                           "math_score": "Math Score", "type": "Type", "size": "Size", "budget":
                                           "Budget"})

renamed

,Student ID,Student Name,Gender,Grade,School Name,Reading Score,Math Score,School ID,type1,Size,Budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
23,23,Christopher Parker,M,9th,Huang High School,81,68,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
26,26,Melanie Decker,F,9th,Huang High School,63,85,0,District,2917,1910635
27,27,Tracey Oconnor,F,10th,Huang High School,80,58,0,District,2917,1910635
28,28,Kelly James,F,11th,Huang High School,73,55,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99,14,Charter,1635,1043130
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93,14,Charter,1635,1043130
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83,14,Charter,1635,1043130
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93,14,Charter,1635,1043130
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87,14,Charter,1635,1043130
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74,14,Charter,1635,1043130
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95,14,Charter,1635,1043130
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81,14,Charter,1635,1043130
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89,14,Charter,1635,1043130
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93,14,Charter,1635,1043130
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75,14,Charter,1635,1043130
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73,14,Charter,1635,1043130
39152,39152,Lori Moore,F,9th,Thomas High School,98,84,14,Charter,1635,1043130
39153,39153,William Hubbard,M,9th,Thomas High School,80,75,14,Charter,1635,1043130
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71,14,Charter,1635,1043130
39155,39155,John Brooks,M,10th,Thomas High School,92,98,14,Charter,1635,1043130
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95,14,Charter,1635,1043130
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94,14,Charter,1635,1043130
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90,14,Charter,1635,1043130
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72,14,Charter,1635,1043130
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86,14,Charter,1635,1043130
39161,39161,April Reyes,F,10th,Thomas High School,70,84,14,Charter,1635,1043130
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77,14,Charter,1635,1043130
39163,39163,John Reese,M,11th,Thomas High School,90,75,14,Charter,1635,1043130
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76,14,Charter,1635,1043130
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130

In [5]:
# look for missing values
school_data_set.count()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
School ID        39170
type1            39170
size             39170
budget           39170
dtype: int64

In [6]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
#no_null_crime_df["Offense Type"].value_counts()
# Combining similar offenses together
#no_null_crime_df["Offense Type"] = no_null_crime_df["Offense Type"].replace(
    #{"Commercial Sex Acts": "Prostitution", "Assisting or Promoting Prostitution": "Prostitution"})
#no_null_crime_df

In [7]:
#Table of total schools, total students, total budget, average math score, average reading score,
# % Passing Math, % Passing Reading, Overall passing rate (average of math and reading)

district_total = school_data_set[["school_name", "student_name", "budget", "reading_score", "math_score"]]
district_total.head()

#I need to tell it count schools, count students, sum budget, average math, average reading,
# figure out what qualifies as passing for percentages for math and reading, sum then average of math and reading

         school_name       student_name   budget  reading_score  math_score
0  Huang High School       Paul Bradley  1910635             66          79
1  Huang High School       Victor Smith  1910635             94          61
2  Huang High School    Kevin Rodriguez  1910635             90          60
3  Huang High School  Dr. Richard Scott  1910635             67          58
4  Huang High School         Bonnie Ray  1910635             97          84

In [8]:
#Total Schools
school_count = len(school_data_set["school_name"].unique())

#Total Students
student_count = len(school_data_set["student_name"].unique())

#Total Budget
budget_sum = school_data_set["budget"].sum()

#Average Reading
avg_reading = school_data_set["reading_score"].mean()

#Average Math
avg_math = school_data_set["math_score"].mean()

#Sum of Reading for below
sum_reading = school_data_set["reading_score"].sum()

#Sum of Math for below
sum_math = school_data_set["math_score"].sum()

#70 or higher, percent of those who passed reading
#my guess is tell it to sum scores of 70 or higher, divide by total/sum, times by 100
pass_read_if = (school_data_set['reading_score']>= 70)
pass_reading_sum = pass_read_if.sum()
pass_reading = (pass_reading_sum / sum_reading) * 100

#70 or higher, percent of those who passed math
pass_math_if = (school_data_set["math_score"] >= 70)
pass_math_sum = pass_math_if.sum()
pass_math = (pass_math_sum / sum_math) * 100

# percent of overall passing rate
#sum then find average of those who passed reading and math, divide by total sum of total sum of each, times by 100
overall_pass = (pass_math + pass_reading) / 2
#Summary DataFrame
district_summary_table = pd.DataFrame({"Total Schools": [school_count], "Total Students": [student_count], "Total Budget":
                                      [budget_sum], "Average Math Score": [avg_math], "Average Reading Score": [avg_reading],
                                      "% Passing Math": [pass_math], "% Passing Reading": [pass_reading],
                                      "% Overall Passing Rate": [overall_pass]})
district_summary_table
#df['total'] = df[['A','B']].sum(axis=1).where(df['A'] > 0, 0)
#df

# Calculate the number of unique authors in the DataFrame
#author_count = len(goodreads_df["Authors"].unique())

# Calculate the earliest/latest year a book was published
#earliest_year = goodreads_df["Publication Year"].min()
#latest_year = goodreads_df["Publication Year"].max()

# Calculate the total reviews for the entire dataset
#total_reviews = goodreads_df["One Star Reviews"].sum() + goodreads_df["Two Star Reviews"].sum(
#) + goodreads_df["Three Star Reviews"].sum() + goodreads_df["Four Star Reviews"].sum() + goodreads_df["Five Star Reviews"].sum()

# Place all of the data found into a summary DataFrame
#summary_table = pd.DataFrame({"Total Unique Authors": author_count,
                              #"Earliest Year": [earliest_year],
                              #"Latest Year": [latest_year],
                              #"Total Reviews": [total_reviews]})
#summary_table

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,32715,82932329558,78.985371,81.87784,0.949301,1.047969,0.998635

In [9]:
school_data_set.columns

Index(['Student ID', 'student_name', 'gender', 'grade', 'school_name',
       'reading_score', 'math_score', 'School ID', 'type1', 'size', 'budget'],
      dtype='object')

In [10]:
#set index/school type
school_type = school_data.set_index(["school_name"])["type1"]

#total students
per_school = school_data_set.groupby("school_name")
total_students = per_school["Student ID"].count()

#total school budget
school_budget = school_data_set.groupby("school_name")["budget"].sum()

#student budget
student_budget = school_budget / total_students

#average math score
avg_math = school_data_set.groupby("school_name")["math_score"].mean()

#average reading score
avg_reading = school_data_set.groupby("school_name")["reading_score"].mean()

#sum math
sum_math = school_data_set.groupby("school_name")["reading_score"].sum()

#sum reading
sum_reading = school_data_set.groupby("school_name")["reading_score"].sum()

#pass math

pass_score = school_data_set.loc[school_data_set['math_score'] >= 70, :].groupby("school_name")
math_students = pass_score['Student ID'].count()
pass_math = (math_students/total_students)*100

#pass reading
pass_read_score = school_data_set.loc[school_data_set['reading_score'] >= 70, :].groupby("school_name")
read_students = pass_read_score['Student ID'].count()
pass_reading = (read_students/total_students)*100


#overall passing
overall_passing = (pass_math + pass_reading)/2

#school_data_set[school_data_set.index.duplicated()]

#dataframe
school_summary = pd.DataFrame({'School Type': school_type, 'Total Students': total_students,
                              'Total School Budget': school_budget, 'Student Budget': student_budget,
                              'Average Math Score': avg_math, 'Average Reading Score': avg_reading,
                              '% Passing Math': pass_math, '% Passing Reading': pass_reading,
                              'Overall Passing Rate': overall_passing})
school_summary



#By Schools - each schools':

#def function(student_budget):
    #stu = student_budget.school_name.count()
    #budg = student_budget.budget.sum()
    #stu_budg = (stu/budg)
#student_budget = school_data_set.groupby("school_name").apply(function)

#def func(pass_math):
    #math_pass = (pass_math.math_score.sum() >=70)
    #math_total = pass_math.math_score.sum()
    #passing_math = (math_pass/math_total) * 100
#stu_math_pass = school_data_set.groupby("school_name").apply(func)

#def funct(pass_reading):
    #read_pass = (pass_reading.reading_score.sum() >=70)
    #read_total = pass_reading.reading_score.sum()
    #passing_read = (read_pass/read_total) * 100
#stu_read_pass = school_data_set.groupby("school_name").apply(funct)

#def func(group):
    #sum_ = group.qty.sum()
    #es = (group.csv / group.qty).sum()
    #return pd.Series([sum_, es], index=['qty', 'es'])

#trades.groupby('ordrefno').apply(func)

#school_by = school_data_set.groupby("school_name").agg({'student_name': "count",'budget': "sum",
                                                       #'reading_score': "mean", 'math_score': "mean"})
#school_by
#df.groupby('A').agg({'B': ['min', 'max'], 'C': 'sum'})
# Group the data frame by month and item and extract a number of stats from each group
#data.groupby(['month', 'item']).agg({'duration':sum,      # find the sum of the durations for each group
                                     #'network_type': "count", # find the number of network type entries
                                     #'date': 'first'})    # get the first date per group
#school_by = school_data_set.groupby("school_name")
#school_by

#School name 
#School type
#Total Students

#data.groupby('month')['duration'].sum()

#Total School Budget

#Per Student Budget - total budget divide by total student (I think), trying function
#Average Math Score - average function
#Average Reading Score - average function
#% Passing Math - sum of students passing divide by sum of math times 100
#% Passing Reading - sum of students passing divide by sum of reading imes 100
#Overall Passing Rate (Average of the above two)
#summary_school_by = pd.DataFrame({"School Name": [schools_name], "School Type": [school_type]})
#summary_school_by

,School Type,Total Students,Total School Budget,Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
Bailey High School,District,4976,15549641728,3124928.0,77.048432,81.033963,66.680064,81.933280,74.306672
Cabrera High School,Charter,1858,2009159448,1081356.0,83.061895,83.975780,94.133477,97.039828,95.586652
Figueroa High School,District,2949,5557128039,1884411.0,76.711767,81.158020,65.988471,80.739234,73.363852
Ford High School,District,2739,4831365924,1763916.0,77.102592,80.746258,68.309602,79.299014,73.804308
Griffin High School,Charter,1468,1346890000,917500.0,83.351499,83.816757,93.392371,97.138965,95.265668
Hernandez High School,District,4635,14007062700,3022020.0,77.289752,80.934412,66.752967,80.862999,73.807983
Holden High School,Charter,427,105933149,248087.0,83.803279,83.814988,92.505855,96.252927,94.379391
Huang High School,District,2917,5573322295,1910635.0,76.629414,81.182722,65.683922,81.316421,73.500171
Johnson High School,District,4761,14733628650,3094650.0,77.072464,80.966394,66.057551,81.222432,73.639992
Pena High School,Charter,962,563595396,585858.0,83.839917,84.044699,94.594595,95.945946,95.270270
Rodriguez High School,District,3999,10186904637,2547363.0,76.842711,80.744686,66.366592,80.220055,73.293323
Shelton High School,Charter,1761,1860672600,1056600.0,83.359455,83.725724,93.867121,95.854628,94.860875
Thomas High School,Charter,1635,1705517550,1043130.0,83.418349,83.848930,93.272171,97.308869,95.290520
Wilson High School,Charter,2283,3012587442,1319574.0,83.274201,83.989488,93.867718,96.539641,95.203679
Wright High School,Charter,1800,1888920000,1049400.0,83.682222,83.955000,93.333333,96.611111,94.972222

In [12]:
#Top 5 schools with above information

top_schools = school_summary.sort_values("Overall Passing Rate", ascending=False)
top_schools.head()
#freedom_df = happiness_df.sort_values("Freedom", ascending=False)
#freedom_df.head()

,School Type,Total Students,Total School Budget,Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
Cabrera High School,Charter,1858,2009159448,1081356.0,83.061895,83.975780,94.133477,97.039828,95.586652
Thomas High School,Charter,1635,1705517550,1043130.0,83.418349,83.848930,93.272171,97.308869,95.290520
Pena High School,Charter,962,563595396,585858.0,83.839917,84.044699,94.594595,95.945946,95.270270
Griffin High School,Charter,1468,1346890000,917500.0,83.351499,83.816757,93.392371,97.138965,95.265668
Wilson High School,Charter,2283,3012587442,1319574.0,83.274201,83.989488,93.867718,96.539641,95.203679

In [13]:
#Worse 5 schools with above information
bottom_schools = school_summary.sort_values("Overall Passing Rate")
bottom_schools.head()

,School Type,Total Students,Total School Budget,Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
Rodriguez High School,District,3999,10186904637,2547363.0,76.842711,80.744686,66.366592,80.220055,73.293323
Figueroa High School,District,2949,5557128039,1884411.0,76.711767,81.158020,65.988471,80.739234,73.363852
Huang High School,District,2917,5573322295,1910635.0,76.629414,81.182722,65.683922,81.316421,73.500171
Johnson High School,District,4761,14733628650,3094650.0,77.072464,80.966394,66.057551,81.222432,73.639992
Ford High School,District,2739,4831365924,1763916.0,77.102592,80.746258,68.309602,79.299014,73.804308

In [36]:
#Math Scores By Grade
#Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.
#Create a pandas series for each grade. Hint: use a conditional statement.
#Group each series by school
#Combine the series into a dataframe
#Optional: give the displayed data cleaner formatting

#index by school name
school_by_math = school_data_set.set_index("school_name")
grade_9 = school_data_set.loc[school_data_set["grade"] == "9"].groupby("school_name") #may need == "9", :].groupby
grade_10 = school_data_set.loc[school_data_set["grade"] == "10"].groupby("school_name")
grade_11 = school_data_set.loc[school_data_set["grade"] == "11"].groupby("school_name")
grade_12 = school_data_set.loc[school_data_set["grade"] == "12"].groupby("school_name")


avg_math = school_data_set.groupby("school_name")["math_score"].mean()
avg_math

math_by_grade = pd.DataFrame({'9th':})

pass_score = school_data_set.loc[school_data_set['math_score'] >= 70, :].groupby("school_name")
math_students = pass_score['Student ID'].count()
pass_math = (math_students/total_students)*100

#ideas for showing grade

#This will only show in the columns and not make new columns, but it's a start
#vernon_crime_df = no_null_crime_df.loc[no_null_crime_df["Neighborhood"] == "Vernon"]
#vernon_crime_df

#school_grades_math = school_data_set.loc[school_data_set["grade" >= 9]]
#school_grades_math = pd.Series(["grades"], index = ['9', '10', '11', '12']) <== does not work
#school_grades_math


# Set new index to last_name
#df = df_original.set_index("last_name")
#df.head()

#school_name_math = school_data_set.set_index(["school_name", "grade"]).agg({'math_score': "mean"})
#school_name_math

#data.groupby(['month', 'item']).agg({'duration':sum,      # find the sum of the durations for each group
                                     #'network_type': "count", # find the number of network type entries
                                     #'date': 'first'})    # get the first date per group


#example of a function groupby
#def get_letter_type(letter):
   #if letter.lower() in 'aeiou':
    #return 'vowel'
#else:
    #return 'consonant'

#grouped = df.groupby(get_letter_type, axis=1)

school_name
Bailey High School       77.048432
Cabrera High School      83.061895
Figueroa High School     76.711767
Ford High School         77.102592
Griffin High School      83.351499
Hernandez High School    77.289752
Holden High School       83.803279
Huang High School        76.629414
Johnson High School      77.072464
Pena High School         83.839917
Rodriguez High School    76.842711
Shelton High School      83.359455
Thomas High School       83.418349
Wilson High School       83.274201
Wright High School       83.682222
Name: math_score, dtype: float64

In [ ]:
#Perform the same operations as above for reading scores

In [ ]:
#Scores by School spending
#Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
#Average Math Score
#Average Reading Score
#% Passing Math
#% Passing Reading
#Overall Passing Rate (Average of the above two)

In [ ]:
#Scores by School size
#Perform the same operations as above, based on school size.

In [ ]:
#Scores by school type
#Perform the same operations as above, based on school type

In [ ]:
# The value_counts method counts unique values in a column
count = data_file_pd["Gender"].value_counts()
count

# Calculations can also be performed on Series and added into DataFrames as new columns
thousands_of_dollars = data_file_pd["Amount"]/1000
data_file_pd["Thousands of Dollars"] = thousands_of_dollars

data_file_pd.head()

# Remove unecessary columns from the DataFrame and save the new DataFrame
# Only keep: "isbn", "original_publication_year", "original_title", "authors",
# "ratings_1", "ratings_2", "ratings_3", "ratings_4", "ratings_5"
reduced_df = books_df[["isbn", "original_publication_year", "original_title", "authors",
                       "ratings_1", "ratings_2", "ratings_3", "ratings_4", "ratings_5"]]
reduced_df.head()